[workspace]
members = [
    "common",
    "contracts/marketplace",
    "contracts/dtoken",
    "contracts/split_policy",
    "contracts/data_id",
    "contracts/accountant",
    "contracts/openkg"
]

[profile.release]
panic = "abort"
lto = true
debug = true
opt-level = "s"