[workspace]
members = [
    "contracts/ddxf",
    "contracts/dtoken",
    "contracts/marketplace",
    "contracts/split_policy"
]

[profile.release]
panic = "abort"
lto = true
debug = true
opt-level = "s"